[[section-deployment-view]]
== Verteilungssicht

[NOTE]
====
Die Infrastruktur ist komplett unklar.
Im echten Projekt würde man hier weitere Informationen beim Kunden einholen müssen:

* Gibt es Infrastruktur, die mitbenutzt werden kann oder soll?
* Gibt es Vorgaben bzgl CloudProvidern?
* Ist externes Hosting erlaubt oder verboten?

Ebenfalls zu klären ist, ob es für den externen Dienst `TurnItIn` eine Testumgebung gibt, welche in der Integrationsumgebung angebunden werden kann.
====

*Annahme*: Es gibt interne Infrastruktur bei der Universität. Dort werden Umgebungen bereitgestellt.
Das Hosting der externen Sandboxes erfolgt bei AWS.

=== Umgebungen

Es werden folgende Umgebungen in der Infrastruktur der Universität eingerichtet:

* Test-Umgebung
* Integrationsumgebung
* Produktivumgebung

Desweiteren werden beim CloudProvider dynamisch Container-Instanzen bereitgestellt.

Die BasisImages werden beim CloudProvider in der Image Registry hochgeladen.

=== Deployment

Alle Komponenten der Anwendung `CheckYourWork` sind in jeder Umgebung jeweils auf einem Server deployt.
Der Code wird in einem Container beim externen CloudProvider compiliert und gestartet.
Diese Container werden dort "on demand" gestartet, so dass eine gewisse Elastizität gewährleistet ist.
Bei jedem Code-Upload eines Studenten wird beim CloudProvider eine eigene Container-Instanz hochgefahren.

NOTE: Hier ist mir auch unklar, wie genau so ein Bild aussehen soll.
Die bei PlantUML sehen alle komisch aus...